import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import stylesAbout from "../styles/About.module.css";
import stylesComponent from "../styles/Component.module.css";
import { useEffect } from "react";

export default function about() {
  useEffect(() => {
    const button = document.querySelector("#menu-button");
    const menu = document.querySelector("#menu");

    button.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  }, []);

  return (
    <div className={stylesAbout.container}>
      <Head>
        <title>mmmacias | Web designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="msticky top-0 z-50">
        <nav
          className="
                my-4
                flex flex-wrap
                items-center
                justify-between
                w-full
                py-4
                
                md:py-0
                text-lg text-gray-700
                "
        >
          <div>
            <a href="/" className={styles.brand}>
              mmmacias
            </a>
          </div>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            id="menu-button"
            className="h-6 w-6 cursor-pointer md:hidden block"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>

          <div
            className="hidden w-full md:flex md:flex-col md:items-center md:w-auto"
            id="menu"
          >
            <ul
              className="
                    pt-4
                    text-base text-black
                    md:flex
                    md:justify-between 
                    md:pt-0"
            >
              <li className={styles.hoverAnimation}>
                <a
                  className="md:p-4 py-2 block"
                  href="/about"
                  rel="noopener noreferrer"
                >
                  about me
                </a>
              </li>
              <li className={styles.hoverAnimation}>
                <a
                  className="md:p-4 py-2 block"
                  href="/contact"
                  rel="noopener noreferrer"
                >
                  contact
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main className={stylesAbout.mainAbout}>
        <div className={stylesAbout.mainTextAbout}>
          <h1 className={styles.title}> I'm Mariana</h1>
          <p className={styles.description}>
            Web Designer & aspiring Front-end Developer.
          </p>
          <br />
          <p className={stylesAbout.bodyText}>
            Hey! I’m Mariana Macías, 26. Web designer and an enthusiast of
            front-end development.{" "}
          </p>
          <br />
          <p className={stylesAbout.bodyText}>
            I have a bachelor degree in Graphic Design, from the Universidad
            Autónoma de Aguascalientes.
            <br />
            Also attended some conferences and courses to learn about UI and UX,
            which are the main reasons I switch from an artistic path to a
            tech-ish one.
          </p>
          <br />
          <ul>
            <li className={stylesAbout.quoteText}>
              <b>“Becoming a data-aware Designer”</b>
              <br />
              <i>Digital Tech Fest (2020)</i>
            </li>
            <li className={stylesAbout.quoteText}>
              <b>”Colaboración UX - Prototipado”</b>
              <br />
              <i>UX Digital Summit (2017)</i>
            </li>
            <li className={stylesAbout.quoteText}>
              <b>”Startup Weekend eCommerce”</b>
              <br />
              <i>Startup Weekend Aguascalientes (2016)</i>
            </li>
          </ul>
          <br />
          <p className={stylesAbout.bodyText}>
            I’ve learned HTML and CSS with online courses and help from fellow
            friends and work colleagues. Recently learning JS and some other
            libraries, such as Vue, React, and React frameworks like Next.js
          </p>
          <br />
          <p className={stylesAbout.bodyText}>
            When I’m not working, I like to do some other activities, like
            cooking and eating stuff I can make with my kitchen appliances
            that’s 100% an adulting thing). Petting and smooching my schnauzer
            doggo, Teo. And singing, nothing formal, I just enjoy singing anime
            songs or something from the Yeah Yeah Yeahs as I do some other
            stuff.
          </p>
          <br />
          <p classsName={stylesAbout.bodyText}>
            This is just a little bit about me! Go and check out some of my{" "}
            <a
              href="/#work"
              className={stylesAbout.workLink}
              rel="noopener noreferrer"
            >
              work
            </a>{" "}
            :)
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p className="text-center">©2021 mmmacias</p>
      </footer>
    </div>
  );
}
