import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import stylesProject from "../styles/Project.module.css";
import stylesComponent from "../styles/Component.module.css";

export default function soundMoods() {
  return (
    <div className={styles.container}>
      <Head>
        <title>mmmacias | Web designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mmm.ico" />
      </Head>
      <header className="msticky top-0 z-50">
        <nav
          className="
                my-4
                flex flex-wrap
                items-center
                justify-between
                w-full
                py-4
                
                md:py-0
                text-lg text-gray-700
                "
        >
          <div>
            <a href="/" className={styles.brand}>
              mmmacias
            </a>
          </div>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            id="menu-button"
            className="h-6 w-6 cursor-pointer md:hidden block"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>

          <div
            className="hidden w-full md:flex md:flex-col md:items-center md:w-auto"
            id="menu"
          >
            <ul
              className="
                    pt-4
                    text-base text-black
                    md:flex
                    md:justify-between 
                    md:pt-0"
            >
              <li className={styles.hoverAnimation}>
                <a className="md:p-4 py-2 block" href="#">
                  about me
                </a>
              </li>
              <li className={styles.hoverAnimation}>
                <a className="md:p-4 py-2 block" href="#">
                  contact
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <main className={stylesProject.main}>
        <div className={stylesProject.headerSm}>
          <h1 className={stylesProject.title}>Sound Moods</h1>
        </div>

        <div className={stylesProject.body}>
          <p className={stylesProject.description}>UI, Personal Project</p>

          <p className={stylesProject.text}>
            This was the last personal project that I made.
            <br />
            <br />
            Most of my current job relies on making design decisions through
            design guidelines, manuals, accesibility, etc. So this was mostly to
            have some fun with the music I'm listening to. (In this case, J-pop
            band, YOASOBI)
          </p>
          <hr className={stylesProject.line} />
          <p className={stylesProject.description}>Color Palette</p>
          <p className={stylesProject.text}>
            The color palette was made with YOASOBI's main color from the single
            Gunjou (群青), making some variations with opacity and saturation.
            For other areas, the use of gradients.
          </p>
          <div className={stylesProject.imgContainer}>
            <Image
              src="/img/sm/palette.png"
              alt="soundmoods-color-palette"
              width={920}
              height={383}
            />
          </div>
          <br />
          <p className={stylesProject.description}>Interface design</p>
          <p className={stylesProject.text}>
            The main screen has 3 sections.
            <br />
            <br />
            <b>My Moods</b> has a list with an horizontal scroll, with the
            playlists you've created.
            <br />
            <b>New</b> is a selection of the latest releases from your favourite
            artists.
            <br />
            <b>Recently loved</b> puts your whole favorite songs in a list.
          </p>
          <div className={stylesProject.imgContainer}>
            <Image
              src="/img/sm/screen1.png"
              alt="soundmoods-screens-one"
              width={920}
              height={725}
            />
          </div>
          <p className={stylesProject.text}>
            Artist section features an intro image with number of
            subscribers/followers, latest release, Most loved songs (as in saved
            by the users), albums and singles with an horizontal scroll.
          </p>
          <div className={stylesProject.imgContainer}>
            <Image
              src="/img/sm/screen2.png"
              alt="soundmoods-screens-one"
              width={920}
              height={769}
            />
          </div>
          <p className={stylesProject.text}>
            A component for locked screens shows the image from what's playing
            at the moment, name of the song, artist, the option to love or
            un-love the song and the usual music controls.
            <br />
            <br />
            In the Playing Now screen, there is the image from the album/single.
            The next row shows at the center song name and artist, at the left
            the queue, and at the right the loved button. The final row, has the
            time bar and the usual music controls (repeat, before, play/pause,
            next and random).
            <br />
            <br />
            In the minimized version, it'll only show the song image. name of
            the song, artist, time bar and play/pause button.
          </p>
          <div className={stylesProject.imgContainer}>
            <Image
              src="/img/sm/screen3.png"
              alt="soundmoods-screens-one"
              width={920}
              height={769}
            />
          </div>
          <hr className={stylesProject.line} />
          <p className={stylesProject.text}>
            And that's it, I know it lacks some of technical and accesibility
            things, but making aesthethically pleasing projects is kind of eye
            candy for me, and I enjoyed the process :)
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p className="text-center">©2021 mmmacias</p>
      </footer>
    </div>
  );
}
