import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import stylesProject from "../styles/Project.module.css";
import stylesComponent from "../styles/Component.module.css";

export default function soundMoods() {
  return (
    <div className={styles.container}>
      <Head>
        <title>mmmacias | Web designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="msticky top-0 z-50">
        <nav
          className="
                my-4
                flex flex-wrap
                items-center
                justify-between
                w-full
                py-4
                
                md:py-0
                text-lg text-gray-700
                "
        >
          <div>
            <a href="/" className={styles.brand}>
              mmmacias
            </a>
          </div>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            id="menu-button"
            className="h-6 w-6 cursor-pointer md:hidden block"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>

          <div
            className="hidden w-full md:flex md:flex-col md:items-center md:w-auto"
            id="menu"
          >
            <ul
              className="
                    pt-4
                    text-base text-black
                    md:flex
                    md:justify-between 
                    md:pt-0"
            >
              <li className={styles.hoverAnimation}>
                <a className="md:p-4 py-2 block" href="#">
                  about me
                </a>
              </li>
              <li className={styles.hoverAnimation}>
                <a className="md:p-4 py-2 block" href="#">
                  contact
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <main className={stylesProject.main}>
        <div className={stylesProject.header}>
          <h1 className={stylesProject.title}>Sound Moods</h1>
        </div>
      </main>
    </div>
  );
}
