import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import stylesContact from "../styles/Contact.module.css";
import stylesComponent from "../styles/Component.module.css";
import { useEffect } from "react";

export default function contact() {
  return (
    <div className={stylesContact.container}>
      <Head>
        <title>mmmacias | Web designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mmm.ico" />
      </Head>
      <header className="msticky top-0 z-50">
        <nav
          className="
                my-4
                flex flex-wrap
                items-center
                justify-between
                w-full
                py-4
                
                md:py-0
                text-lg text-gray-700
                "
        >
          <div>
            <Link href="/" className={styles.brand}>
              mmmacias
            </Link>
          </div>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            id="menu-button"
            className="h-6 w-6 cursor-pointer md:hidden block"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>

          <div
            className="hidden w-full md:flex md:flex-col md:items-center md:w-auto"
            id="menu"
          >
            <ul
              className="
                    pt-4
                    text-base text-black
                    md:flex
                    md:justify-between 
                    md:pt-0"
            >
              <li className={styles.hoverAnimation}>
                <Link
                  className="md:p-4 py-2 block"
                  href="/about"
                  rel="noopener noreferrer"
                >
                  about me
                </Link>
              </li>
              <li className={styles.hoverAnimation}>
                <Link
                  className="md:p-4 py-2 block"
                  href="/contact"
                  rel="noopener noreferrer"
                >
                  contact
                </Link>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main className={stylesContact.main}>
        <div className={stylesContact.contactImgContainer}>
          <Image src="/img/contact.png" width={440} height={285} alt="contact-image" />
        </div>
        <div className={stylesContact.divider}></div>
        <div className={stylesContact.contactText}>
          <h1 className={styles.title}>Contact</h1>
          <br />
          <a
            href="mailto:mariana.macias2395@gmail.com"
            target="_blank"
            rel="noopener noreferrer"
            className={stylesContact.infoContainer}
          >
            <Image
              src="/img/icons/ic_round-mail.jpg"
              alt="icon-mail"
              width={41}
              height={25}
            />
            <p className={stylesContact.text}>marianamacias2395@gmail.com</p>
          </a>
          <a
            href="https://www.behance.net/marianamacias2395"
            target="_blank"
            rel="noopener noreferrer"
            className={stylesContact.infoContainer}
          >
            <Image
              src="/img/icons/ic_behance.jpg"
              alt="icon-behance"
              width={41}
              height={25}
            />
            <p className={stylesContact.text}>/marianamacias2395</p>
          </a>
          <a
            href="https://www.linkedin.com/in/mariana-macias2395/"
            target="_blank"
            rel="noopener noreferrer"
            className={stylesContact.infoContainer}
          >
            <Image
              src="/img/icons/ic_linkedin.jpg"
              alt="icon-linkedin"
              width={41}
              height={25}
            />
            <p className={stylesContact.text}>/mariana-macias2395</p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <p className="text-center">©2021 mmmacias</p>
      </footer>
    </div>
  );
}
